import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core"
import { generateId } from "@/utils/uuid"

// ============================================================================
// Auth tables (generated by better-auth)
// ============================================================================

const users = sqliteTable("users", {
  id: text("id").primaryKey().$defaultFn(generateId),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: integer("email_verified", { mode: "boolean" }).notNull().default(false),
  image: text("image"),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date())
    .$onUpdate(() => new Date()),
})

const sessions = sqliteTable("sessions", {
  id: text("id").primaryKey().$defaultFn(generateId),
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  token: text("token").notNull().unique(),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date())
    .$onUpdate(() => new Date()),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
})

const accounts = sqliteTable("accounts", {
  id: text("id").primaryKey().$defaultFn(generateId),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: integer("access_token_expires_at", { mode: "timestamp" }),
  refreshTokenExpiresAt: integer("refresh_token_expires_at", { mode: "timestamp" }),
  scope: text("scope"),
  password: text("password"),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date())
    .$onUpdate(() => new Date()),
})

const verifications = sqliteTable("verifications", {
  id: text("id").primaryKey().$defaultFn(generateId),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .$defaultFn(() => new Date())
    .$onUpdate(() => new Date()),
})

// ============================================================================
// App-specific tables
// ============================================================================

/**
 * Apple Music tokens - stores MusicKit user tokens per user
 */
const appleMusicTokens = sqliteTable("apple_music_tokens", {
  id: text("id").primaryKey().$defaultFn(generateId),
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" })
    .unique(),
  userToken: text("user_token").notNull(),
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date())
    .$onUpdate(() => new Date()),
})

/**
 * Tracks - listening history per user
 */
const tracks = sqliteTable("tracks", {
  id: text("id").primaryKey().$defaultFn(generateId),
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  trackId: text("track_id").notNull(), // Apple Music track ID
  name: text("name").notNull(),
  artistName: text("artist_name").notNull(),
  albumName: text("album_name").notNull(),
  durationMs: integer("duration_ms").notNull(),
  data: text("data"), // JSON string of full Apple Music response
  playedAt: integer("played_at", { mode: "timestamp" }).notNull(),
  syncedToCalendar: integer("synced_to_calendar", { mode: "boolean" }).notNull().default(false),
  calendarEventId: text("calendar_event_id"),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date())
    .$onUpdate(() => new Date()),
})

/**
 * Sync state - per-user sync state
 */
const syncState = sqliteTable("sync_state", {
  id: text("id").primaryKey().$defaultFn(generateId),
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" })
    .unique(),
  lastSeenTrackIds: text("last_seen_track_ids"), // JSON array of track IDs
  initialized: integer("initialized", { mode: "boolean" }).notNull().default(false),
  lastSyncAt: integer("last_sync_at", { mode: "timestamp" }),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date())
    .$onUpdate(() => new Date()),
})

// Type exports
type UserRow = typeof users.$inferSelect
type NewUserRow = typeof users.$inferInsert
type SessionRow = typeof sessions.$inferSelect
type AccountRow = typeof accounts.$inferSelect
type AppleMusicTokenRow = typeof appleMusicTokens.$inferSelect
type NewAppleMusicTokenRow = typeof appleMusicTokens.$inferInsert
type TrackRow = typeof tracks.$inferSelect
type NewTrackRow = typeof tracks.$inferInsert
type SyncStateRow = typeof syncState.$inferSelect
type NewSyncStateRow = typeof syncState.$inferInsert

export { users, sessions, accounts, verifications, appleMusicTokens, tracks, syncState }

export type {
  UserRow,
  NewUserRow,
  SessionRow,
  AccountRow,
  AppleMusicTokenRow,
  NewAppleMusicTokenRow,
  TrackRow,
  NewTrackRow,
  SyncStateRow,
  NewSyncStateRow,
}
