/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAppleMusicTokenRouteImport } from './routes/api/apple-music/token'
import { Route as ApiAppleMusicConnectRouteImport } from './routes/api/apple-music/connect'

const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/(marketing)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/(app)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppleMusicTokenRoute = ApiAppleMusicTokenRouteImport.update({
  id: '/api/apple-music/token',
  path: '/api/apple-music/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppleMusicConnectRoute = ApiAppleMusicConnectRouteImport.update({
  id: '/api/apple-music/connect',
  path: '/api/apple-music/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof appDashboardRoute
  '/api/cron': typeof ApiCronRoute
  '/': typeof marketingIndexRoute
  '/api/apple-music/connect': typeof ApiAppleMusicConnectRoute
  '/api/apple-music/token': typeof ApiAppleMusicTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof appDashboardRoute
  '/api/cron': typeof ApiCronRoute
  '/': typeof marketingIndexRoute
  '/api/apple-music/connect': typeof ApiAppleMusicConnectRoute
  '/api/apple-music/token': typeof ApiAppleMusicTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/dashboard': typeof appDashboardRoute
  '/api/cron': typeof ApiCronRoute
  '/(marketing)/': typeof marketingIndexRoute
  '/api/apple-music/connect': typeof ApiAppleMusicConnectRoute
  '/api/apple-music/token': typeof ApiAppleMusicTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/api/cron'
    | '/'
    | '/api/apple-music/connect'
    | '/api/apple-music/token'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/api/cron'
    | '/'
    | '/api/apple-music/connect'
    | '/api/apple-music/token'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/(app)/dashboard'
    | '/api/cron'
    | '/(marketing)/'
    | '/api/apple-music/connect'
    | '/api/apple-music/token'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appDashboardRoute: typeof appDashboardRoute
  ApiCronRoute: typeof ApiCronRoute
  marketingIndexRoute: typeof marketingIndexRoute
  ApiAppleMusicConnectRoute: typeof ApiAppleMusicConnectRoute
  ApiAppleMusicTokenRoute: typeof ApiAppleMusicTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apple-music/token': {
      id: '/api/apple-music/token'
      path: '/api/apple-music/token'
      fullPath: '/api/apple-music/token'
      preLoaderRoute: typeof ApiAppleMusicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apple-music/connect': {
      id: '/api/apple-music/connect'
      path: '/api/apple-music/connect'
      fullPath: '/api/apple-music/connect'
      preLoaderRoute: typeof ApiAppleMusicConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  appDashboardRoute: appDashboardRoute,
  ApiCronRoute: ApiCronRoute,
  marketingIndexRoute: marketingIndexRoute,
  ApiAppleMusicConnectRoute: ApiAppleMusicConnectRoute,
  ApiAppleMusicTokenRoute: ApiAppleMusicTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
